wykres-float:
	python3 num1.py float wykres

wykres-double:
	python3 num1.py double wykres

blad-float:
	python3 num1.py float blad

blad-double:
	python3 num1.py double blad

# To compile those programs type:		
# make wykres-float					
# make wykres-double
# make blad-float
# make blad-double					
